const compostiChimici = [
    {"nome": "Acqua", "formula": "H2O"},
    {"nome": "Anidride Carbonica", "formula": "CO2"},
    {"nome": "Sale da Cucina", "formula": "NaCl"},
    {"nome": "Glucosio", "formula": "C6H12O6"},
    {"nome": "Etanolo", "formula": "C2H5OH"},
    {"nome": "Ammoniaca", "formula": "NH3"},
    {"nome": "Metano", "formula": "CH4"},
    {"nome": "Ossigeno", "formula": "O2"},
    {"nome": "Azoto", "formula": "N2"},
    {"nome": "Idrogeno", "formula": "H2"},
    {"nome": "Benzene", "formula": "C6H6"},
    {"nome": "Caffeina", "formula": "C8H10N4O2"},
    {"nome": "Propano", "formula": "C3H8"},
    {"nome": "Perossido d'idrogeno", "formula": "H2O2"},
    {"nome": "Acido acetico", "formula": "CH3COOH"},
    {"nome": "Saccarosio", "formula": "C12H22O11"},
    {"nome": "Acido citrico", "formula": "C6H8O7"},
    {"nome": "Isopropanolo", "formula": "C3H7OH"},
    {"nome": "Butano", "formula": "C4H10"},
    {"nome": "Acido stearico", "formula": "C18H36O2"},
    {"nome": "Acetone", "formula": "CH3COCH3"},
    {"nome": "Acido acetico", "formula": "C2H4O2"},
    {"nome": "Toluene", "formula": "C7H8"},
    {"nome": "Cicloesano", "formula": "C6H12"},
    {"nome": "Ottano", "formula": "C8H18"},
    {"nome": "Decano", "formula": "C10H22"},
    {"nome": "Esadecano", "formula": "C16H34"},
    {"nome": "Pentano", "formula": "C5H12"},
    {"nome": "Eptano", "formula": "C7H14"},
    {"nome": "Glicina", "formula": "C2H5NO2"},
    {"nome": "Butanolo", "formula": "C4H10O"},
    {"nome": "Fenolo", "formula": "C7H8O"},
    {"nome": "Acido acetilsalicilico", "formula": "C4H4O2"},
    {"nome": "Fenolo", "formula": "C6H5OH"},
    {"nome": "Acido benzoico", "formula": "C7H6O2"},
    {"nome": "Etere di etilenglicole", "formula": "C5H10O2"},
    {"nome": "Acido aspartico", "formula": "C2H3NO2"},
    {"nome": "Acido butirrico", "formula": "C4H8O2"},
    {"nome": "Acido ascorbico", "formula": "C6H8O7"},
    {"nome": "Acido benzoico", "formula": "C8H8O3"},
    {"nome": "Nitrofenolo", "formula": "C6H5NO2"},
    {"nome": "Toluene", "formula": "C8H10"},
    {"nome": "Acido adipico", "formula": "C8H14O2"},
    {"nome": "Acido propionico", "formula": "C3H4O2"},
    {"nome": "Acido anisico", "formula": "C9H10O2"},
    {"nome": "Trietilenglicole", "formula": "C4H10O3"},
    {"nome": "Limonene", "formula": "C7H12O3"},
    {"nome": "Decanal", "formula": "C10H20O"}
]

var randomFormula = Math.floor(Math.random() * (compostiChimici.length));

document.querySelector('.card-content.formula .nome').innerHTML = compostiChimici[randomFormula].nome;
document.querySelector('.card-content.formula .formula').innerHTML = compostiChimici[randomFormula].formula;